### ISSUE TITLE
Request: how to find the older build files for Fedora 35?

### ISSUE THREAD

**Issue by leukimi** [BarbossHack/Signal-Desktop-Fedora#1]
Due to some issues with `Fedora 36`, I am kind of forced to backtrack to `Fedora 35` for a while until some software bugs are cleared.

The newest version of your code seems to be for `Fedora 36` only. Where do I find the files for `Fedora 35`, that you had here previously that should still work? Which commit is for `Fedora 35`? Maybe it would be good to set a branch for `Fedora 35`.

**Comment by BarbossHack** [comment]
Hi,
You can pull the very last version, and change the fedora version to 35 in the **_FEDORA_VERSION_** file, and then run the Makefile to build the RPM for fedora 35 :+1:
