### ISSUE TITLE
Error: This repository is over its data quota.

### ISSUE THREAD

**Issue by leukimi** [BarbossHack/Signal-Desktop-Fedora#2]
### Not sure how to remedy this error

- This repository is over its data quota.
- Account responsible for LFS bandwidth should purchase more data packs to restore access.

Any idea what this means other than what it says? Any workaround?

```sh
$ make
make: [Makefile:21: clean] Error 1 (ignored)
STEP 1/9: FROM docker.io/fedora:35
STEP 2/9: RUN dnf update -y &&     dnf install -y unzip g++ npm python make gcc git rpm-build libxcrypt-compat patch
--> Using cache f0632ab100ef8ba3c8c93370971584011f56379f0fba967011d0e1ee2ebc441c
--> f0632ab100e
STEP 3/9: RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.rpm.sh | bash &&     dnf install -y git-lfs &&     git lfs install
--> Using cache 34f28e6ca497fd470a8003a55b86dbd1f2101d9739224f782fa240fd8cec76a3
--> 34f28e6ca49
STEP 4/9: ARG SIGNAL_VERSION
--> Using cache fbad44b28de75dee03ba1e8ad21e855f7ca34768ebcfd0eab2d8c315fc9db3b3
--> fbad44b28de
STEP 5/9: ENV NVM_DIR /root/.nvm
--> Using cache ead8d1fb2d24b8203d90b57551c2e5a096d84079389ee12cc73d5fadec825715
--> ead8d1fb2d2
STEP 6/9: RUN npm install --global yarn &&     curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash &&     source /root/.nvm/nvm.sh --no-use &&     nvm install $(curl -o- https://raw.githubusercontent.com/signalapp/Signal-Desktop/v${SIGNAL_VERSION}/.nvmrc)
--> Using cache 6180d60ccfc16c6c9777d86b02f04b7cbd674dd7b49374ad3c05b8c417811c76
--> 6180d60ccfc
STEP 7/9: COPY package.json.patch /root/package.json.patch
--> Using cache 6bd22283c8b2dbd1a30f08f7f0512dcda9071208613dc79ad40d3ab85191c6f7
--> 6bd22283c8b
STEP 8/9: RUN cd /root &&     git clone -b v${SIGNAL_VERSION} --depth 1 https://github.com/signalapp/Signal-Desktop.git &&     patch /root/Signal-Desktop/package.json /root/package.json.patch
--> Using cache 37054d4bd478e060a6b55438e1ea8a5e05507678f623f86e4cf3623de7eac551
--> 37054d4bd47
STEP 9/9: RUN cd /root/Signal-Desktop &&     source /root/.nvm/nvm.sh --no-use &&     nvm use &&     yarn install --frozen-lockfileyarn &&     yarn generate &&     yarn build-release
Found '/root/Signal-Desktop/.nvmrc' with version <16.13.2>
Now using node v16.13.2 (npm v8.1.2)
yarn install v1.22.19
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: clone https://github.com/signalapp/better-sqlite3 /usr/local/share/.cache/yarn/v6/.tmp/6b9ea74d442c0d03a1b4c2a1b8696978
Directory: /root/Signal-Desktop
Output:
Cloning into '/usr/local/share/.cache/yarn/v6/.tmp/6b9ea74d442c0d03a1b4c2a1b8696978'...
Downloading deps/sqlcipher.tar.gz (28 MB)
Error downloading object: deps/sqlcipher.tar.gz (a23d694): Smudge error: Error downloading deps/sqlcipher.tar.gz (a23d6941a63307a5aec6a62d260d44406c378462b1d2e16b867f37817db20132): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to '/usr/local/share/.cache/yarn/v6/.tmp/6b9ea74d442c0d03a1b4c2a1b8696978/.git/lfs/logs/20220709T173019.190087361.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: deps/sqlcipher.tar.gz: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by BarbossHack** [comment]
It means what it says unfortunately, Signal repo https://github.com/signalapp/better-sqlite3/ contains a "big" LFS file that everybody is trying to download while cloning, so this repo exceed [max LFS bandwidth for free github accounts](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage)

I openend an issue yesterday to ask Signal to remove this LFS file (or to pay for more bandwidth...) : https://github.com/signalapp/better-sqlite3/issues/6

I will try to find a workaround in the mean time

**Comment by BarbossHack** [comment]
I successfully exclude LFS file `deps/sqlcipher.tar.gz` by adding 
```dockerfile
RUN git config --global lfs.fetchexclude deps/sqlcipher.tar.gz
```
but the Signal-Desktop build process does need this file (or it fails) to build with Signal-Desktop with sqlcipher (which is the only reason Signal forked this repo, they added sqlcipher support to better-sqlite3)

So I don't think we can find a workaround, we have to wait for Signal answer here https://github.com/signalapp/better-sqlite3/issues/6 (we just have to wait for them to face the same problem while building their own project^^)

**Comment by leukimi** [comment]
Thank you for trying to find a workaround.

Does `sqlcipher.tar.gz` exist somewhere else so it can be downloaded in a paralell process which does not fail?

In the *very long* thread in how to get it to compile on Fedora we agree on that it would be so much easier if the project had their own repo(s) for all the major distributions (Fedora, OpenSUSE, Archlinux/Manjaro) and not just Debian/Ubuntu.

Especially true with `Ubuntu 22.04`, some machines that were supported in `Ubuntu 20.04` are not supported longer, forcing those machines to `Manjaro`. All of a sudden, the graphic cards were no longer supported by `Ubuntu 22.04`. Everything worked in `20.04`, why not just add them in `22.04`. Of course there must be a reason for it, but the reason is unknown. Nobody knows why some graphic cards and autdio drivers are no longer there in `22.04`, but that is the reality. Ubuntu used to be the *support-them-all*-distro but now `Manjaro` seems to do that instead. And some machines will only accept `Fedora` because the built in PCI graphic card is broken so the legacy graphic card from the motherboard, usually some Intel chip, can be used instead. Ubuntu does not discover a faulty graphic card and use the legacy automatically, and with every update you have to miss with grub causing you to have a black screen pretty much random. Those funnies on semi working hardware...

Otherwise, the *easy* way is to go for Debian-based distribution which is supported by the project, if the machine can run it.

**Comment by BarbossHack** [comment]
Fixed with https://github.com/BarbossHack/Signal-Desktop-Fedora/commit/b1164243571c37ac10e1e0452a4d85710501b649

**Comment by BarbossHack** [comment]
> In the _very long_ thread about how to get it to compile on Fedora we agree on that it would be so much easier if the project had their own repo(s) for all the major distributions (Fedora, OpenSUSE, Archlinux/Manjaro) and not just Debian/Ubuntu.

Totaly agree, but as long as Signal doesn't have any official repo for fedora I will continue to build my own rpm (as I don't want to go for Debian-based distribution...)
