### ISSUE TITLE
Resolution field "color-string@1.7.4" incompatible with requested version "color-string@^1.9.0"

### ISSUE THREAD

**Issue by leukimi** [BarbossHack/Signal-Desktop-Fedora#3]
You might want to patch this warning too:

`warning Resolution field "color-string@1.7.4" is incompatible with requested version "color-string@^1.9.0"`

`package.json` has `color-string@1.7.4`. Should probably be `color-string@^1.9.0`

```sh
# Edit package.json to add the options 'rpm' and 'AppImage'
python3 <<EOF
query = '''
    "sharp/color/color-string": "1.7.4"
  },
'''
replacement = '''
    "sharp/color/color-string": "1.9.0"
  },
'''
data = None
with open("package.json",'r') as file:
    data = file.read()
    data = data.replace(query,replacement)
with open("package.json",'w') as file:
    file.write(data)
EOF
```

Then the warning should disappear.

**Comment by BarbossHack** [comment]
Thank you for the fix !

But I think it's not my responsability to fix these little warnings, as they are not related to the **RPM** build process, but to Signal-Desktop project itself (you will have the same warning when building on Debian-based distrib too). Maybe you should open a pull request to fix the package.json directly on [Signal-Desktop repo](https://github.com/signalapp/Signal-Desktop) ?

**Comment by leukimi** [comment]
Sorry, didn't mean to upset. You are right. 💙

I have still not been able to compile it for `Fedora 35`.

Maybe network problems or something that makes it bail out so I tried to search for clues what could be wrong in the log, and then I found that one. Of course it is not your responsibility to fix issues of their code. 

Building 4th time here, let's see if it can complete the RPM... there are other errors like updating "node-abi" and such visible, so I guess they have some things to fix, but it doesn't seem to stop the build process.

I assume you managed to build it for `Fedora 36` today?

**Comment by leukimi** [comment]
> Maybe you should open a pull request to fix the `package.json` directly on [Signal-Desktop repo](https://github.com/signalapp/Signal-Desktop) ?

[#6021](https://github.com/signalapp/Signal-Desktop/issues/6021#issue-1299991653)

**Comment by BarbossHack** [comment]
I'm not upset at all :+1: sorry if my last message gave that impression^^

> there are other errors like updating "node-abi"

Indeed, I always have seen this error, but since it's not related to `fedora` and it doesn't stop the build process, I never looked into it :angel: 

> I assume you managed to build it for Fedora 36 today?

Yeah I managed to build it for fedora 36 today (I just upgraded my client to 5.49.0 without any issue), and I just build it for fedora 35 too... Can you share the full build output please ?

**Comment by leukimi** [comment]
#### Welcome to the world:

📦 signal-desktop-5.49.0.fc35.x86_64.rpm

I am curious where on my machine this was built. I searched for the data and it was not even seen :-) not in `/tmp` not in `var/temp` but maybe in the caches in $HOME directory... it is true magic how Docker does this.

**Comment by leukimi** [comment]
Here is the log as attached file.

[📄 log.txt](https://github.com/BarbossHack/Signal-Desktop-Fedora/files/9079698/log.txt)

Hope that is readable.
.

**Comment by BarbossHack** [comment]
> #### Welcome to the world:
> package signal-desktop-5.49.0.fc35.x86_64.rpm
> 
> I am curious where on my machine this was built. I searched for the data and it was not even seen :-) not in `/tmp` not in `var/temp` but maybe in the caches in $HOME directory... it is true magic how Docker does this.

Well, if it was built with my script (Signal-Desktop-Fedora), the file should be within the `output` folder, and you will be able to install it with `make install`

But I think the filename you gave, `signal-desktop-5.49.0.fc35.x86_64.rpm`, was not build with `Signal-Desktop-Fedora`, as the filename should be `signal-desktop-5.49.0.x86_64.rpm` with my script... where do you find it ? ^^

**Comment by BarbossHack** [comment]
> Here is the log as attached file.
> 
> [page_facing_up log.txt](https://github.com/BarbossHack/Signal-Desktop-Fedora/files/9079698/log.txt)
> 
> Hope that is readable.

It seems that the build was successull, try to run `make install` now :+1:

**Comment by BarbossHack** [comment]
> Here is the log as attached file.
> 
> [page_facing_up log.txt](https://github.com/BarbossHack/Signal-Desktop-Fedora/files/9079698/log.txt)
> 
> Hope that is readable.

Indeed, like you though, it comes from your connection having issues : 
```
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/rxjs/-/rxjs-6.6.7.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/root/Signal-Desktop/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
``` 
This error should not happen

But it seems like the last time you runned `make`, the build was successfull, try to run `make install` now :+1:

**Comment by leukimi** [comment]
>  But I think the filename you gave, `signal-desktop-5.49.0.fc35.x86_64.rpm`, was not build with `Signal-Desktop-Fedora`, as the filename should be `signal-desktop-5.49.0.x86_64.rpm` with my script... where do you find it ?

I renamed it manually so that I don't accidentally install it on Fedora 36 later. The fc35 is a standard identifier for version 35. fc36 is for Fedora 36 so I typed it in to be sure I know what it is.

**Comment by BarbossHack** [comment]
As it's solved I will close, but feel free to open new issues if needed :+1:
