### ISSUE TITLE
Add ability to auto-detect FEDORA_VERSION and SIGNAL_VERSION args

### ISSUE THREAD

**Issue by ettubrute47** [BarbossHack/Signal-Desktop-Fedora#9]
You can get the latest signal version from the tags on the remote repo via the following code:

```bash
    tags=$(git ls-remote --tags https://github.com/signalapp/Signal-Desktop.git | awk -F/ '{print $NF}' | grep -v '\-beta' | grep -v '\^{}')
    latest_version=$(echo "$tags" | sort -V | tail -n 1)
```

And you can get the fedora version of the host machine via:

```bash
fedora_version=$(if [ -f /etc/os-release ]; then . /etc/os-release && [ "$ID" = "fedora" ] && echo "$VERSION_ID"; else echo ""; fi)
```

I wrote a small bash script that you run before 'make' that uses these snippets to set the SIGNAL_VERSION and FEDORA_VERSION files, and the script lets the user overwrite the detected signal/fedora versions in case there is an issue or something. You may want to add to Makefile instead, or you may just want to keep manually updating so you can also test it each time, but I wanted to share this in case you find it useful.

**Comment by BarbossHack** [comment]
Thank you for your suggestion !

I've added a `make update` command based on your script, so you can run 
```bash
make update
make
```

**Comment by BarbossHack** [comment]
added in https://github.com/BarbossHack/Signal-Desktop-Fedora/commit/26236f200ee08302ea5d0b69b52128170d65b14d

available in master
